# Generated by Django 5.1.6 on 2025-03-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_plan_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='automated_replies',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='contact_groups',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='contacts_per_group',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='plan',
            name='message_limit',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='simultaneous_campaigns',
            field=models.IntegerField(default=2),
        ),
    ]
