# Generated by Django 5.1.6 on 2025-03-25 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_plan_automated_replies_plan_contact_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='role',
        ),
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(default='default_permission', max_length=100),
        ),
        migrations.CreateModel(
            name='PlanPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.permission')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plan')),
            ],
            options={
                'unique_together': {('plan', 'permission')},
            },
        ),
    ]
